version: '3.3'

services:
  fw-proxy:
    image: theohbrothers/docker-nginx-forward-proxy
    ports:
      - "3128:3128"
    volumes:
      - ./conf/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro      
      - ./conf/htpasswd:/usr/local/nginx/conf/htpasswd:ro      
  scimple:
    image: tirasa/scimple-server:1.0.0        
